plugins {
    id 'com.android.application'
}

android {
    namespace 'com.helasub.app'
    compileSdk 35

    defaultConfig {
        applicationId "com.helasub.app"
        minSdk 21
        targetSdk 35
        versionCode 2
        versionName "1.1"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    // 🔥 [SUPER FIX] පරණ සහ අලුත් Kotlin ලයිබ්‍රරි හැප්පෙන එක මෙතනින් වළක්වනවා
    configurations.all {
        resolutionStrategy {
            exclude group: "org.jetbrains.kotlin", module: "kotlin-stdlib-jdk8"
            exclude group: "org.jetbrains.kotlin", module: "kotlin-stdlib-jdk7"
        }
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:1.7.0"
}
