plugins {
    id 'com.android.application'
}

android {
    namespace 'com.helasub.app'
    compileSdk 34 // 🔥 TV සඳහා වඩාත්ම ස්ථාවර 34 (Android 14) දක්වා සකස් කළා

    defaultConfig {
        applicationId "com.helasub.app"
        minSdk 21
        targetSdk 34 // 🔥 TV එකේ ක්‍රෑෂ් වීම් වැළැක්වීමට 34 කළා
        versionCode 3
        versionName "1.2"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    configurations.all {
        resolutionStrategy {
            exclude group: "org.jetbrains.kotlin", module: "kotlin-stdlib-jdk8"
            exclude group: "org.jetbrains.kotlin", module: "kotlin-stdlib-jdk7"
        }
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:1.6.1" // TV සඳහා ස්ටේබල් වර්ෂන් එක
}
